### ISSUE TITLE
Possible startup bug

### ISSUE THREAD

**Issue by davisp** [alloy/kicker#1]
Just installed this and couldn't for the life of me get it to accept a command. I eventually tracked things down to find that this:

lib/kicker/validate.rb Line 10:
if process_chain.empty?

Changing that to
if process_chain.empty? && pre_process_chain.empty?

Seems to have fixed it peachy keen.

**Comment by cristibalan** [comment]
Thanks for the report. I accidentally broke this in 1.9.2.

Fixed it and released 1.9.3 which should be in the gem repo soon, github willing.
