### ISSUE TITLE
Use a pure Ruby implementation for Growl instead of RubyCocoa

### ISSUE THREAD

**Issue by Manfred** [alloy/kicker#16]
Instead of skipping the Growl code entirely on non-RubyCocoa enabled Rubies we probably want to use: https://github.com/drbrain/ruby-growl.

**Comment by uhlenbrock** [comment]
+1 — RVM doesn't seem to install the RubyCocoa libraries.

**Comment by Manfred** [comment]
The downside of this is that people need to run the Growl server ("Listen for incoming notifications"). I haven't found a way around it, I assume there is none.

**Comment by alloy** [comment]
Does it break kicker if Growl isn’t listening for notifications? Otherwise I’d say it’s good enough.

**Comment by uhlenbrock** [comment]
Would relying on the growlnotify cli be even simpler?

**Comment by Manfred** [comment]
I guess we could have notification support with multiple backends and figure which one is usable.

**Comment by alloy** [comment]
For now I have dropped Growl support completely in the version 3.0.0 branch, which will use OS X 10.8’s User Notifications.

Patches add (working) Growl support for other systems will be accepted.
