### ISSUE TITLE
Is activesupport a dependancy?

### ISSUE THREAD

**Issue by smebberson** [alloy/kicker#17]
Full version information is ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-darwin10.7.4].

When I try to run any kicker command, for example **$ kicker**

I get the following error:

/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- active_support/core_ext/module (LoadError)
    from /Users/smebberson/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'

Once I had a look at the source, I install the activesupport ruby gem and things started working...

Are you able to add it as a dependancy so that it automatically installs?

**Comment by jhogendorn** [comment]
yes, i found i had to install activesupport and i18n to get kicker happy

**Comment by sjl** [comment]
Same here, `gem install activesupport` and `gem install i18n` fixed things.

**Comment by honza** [comment]
Neither `gem install activesupport` nor `gem install i18n` fixed this for me.

```
/Users/honza/.rvm/gems/ruby-1.9.2-p290@project/gems/activesupport-3.2.0/lib/active_support/core_ext/module/deprecation.rb:7:in `deprecate': uninitialized constant ActiveSupport::Deprecation (NameError)
```

**Comment by spraints** [comment]
I get the error about deprecation from activesupport 3.2.\* also. Activesupport 3.1.3 works for me.

Gemfile:

```
source :rubygems
gem 'kicker' ; gem 'activesupport', '3.1.3' ; gem 'i18n'
```

Gemfile.lock:

```

GEM
  remote: http://rubygems.org/
  specs:
    activesupport (3.1.3)
      multi_json (~> 1.0)
    i18n (0.6.0)
    kicker (2.3.1)
      rb-fsevent
    multi_json (1.0.4)
    rb-fsevent (0.9.0)

PLATFORMS
  ruby
  x86-mingw32

DEPENDENCIES
  activesupport (= 3.1.3)
  i18n
  kicker
```

**Comment by Manfred** [comment]
Kicker should only require Active Support when you load the Rails recipe and not in other cases.

Failure to run on ActiveSupport 3.2 has something to do with the module / class structure changing.

 I'll try to figure out what's going on.

**Comment by spraints** [comment]
huh. I wonder what I did to load the rails recipe. Here's my project's .kick file:

``` ruby
process do |files|
  if files.any? { |file| file =~ /\.(cs|csproj|sln)$/ }
    execute 'xbuild'
  end
end
```

I run it simply with `kicker` (or `bundle exec kicker`). When I run without activesupport, I get this error:

```
/usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/gems/kicker-2.3.1/lib/kicker/recipes/rails.rb:3:in `require': cannot load such file -- active_support/core_ext/module (LoadError)
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/gems/kicker-2.3.1/lib/kicker/recipes/rails.rb:3:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/gems/kicker-2.3.1/lib/kicker/recipes.rb:56:in `require'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/gems/kicker-2.3.1/lib/kicker/recipes.rb:56:in `block in <module:Recipes>'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/gems/kicker-2.3.1/lib/kicker/recipes.rb:56:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/gems/kicker-2.3.1/lib/kicker/recipes.rb:56:in `<module:Recipes>'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/gems/kicker-2.3.1/lib/kicker/recipes.rb:30:in `<class:Kicker>'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/gems/kicker-2.3.1/lib/kicker/recipes.rb:29:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/gems/kicker-2.3.1/lib/kicker.rb:122:in `require'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/gems/kicker-2.3.1/lib/kicker.rb:122:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/gems/kicker-2.3.1/bin/kicker:9:in `require'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/gems/kicker-2.3.1/bin/kicker:9:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/bin/kicker:19:in `load'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@git-tfs/bin/kicker:19:in `<main>'
```

I don't think I did anything to make the rails recipe load. What triggers it to load?

**Comment by Manfred** [comment]
Sorry, I meant it _should_ work that way. Currently it just loads all recipes on startup. Working on a fix.

**Comment by spraints** [comment]
no problem. i was just curious. :)

**Comment by Manfred** [comment]
Kicker 2.4.0 should no longer require ActiveSupport. Please give it a try.

**Comment by honza** [comment]
Awesomeness! It works like a charm.

**Comment by spraints** [comment]
works great here, too. thanks!

**Comment by Manfred** [comment]
Good to hear! Have fun (;
