### ISSUE TITLE
Notifications don't works with new Growl version?

### ISSUE THREAD

**Issue by stefanosala** [alloy/kicker#18]
Hi,
i just updated tu Growl 1.3.1 and it seems that notifications gone away, they don't appear anymore.
There is something that i can check?

Thanks!

**Comment by jjaffeux** [comment]
Same here.

**Comment by alloy** [comment]
Sorry, I don’t have Growl 1.3.1, yet. Does it work with other apps? Because it seems more people are having issues with 1.3.1 (on the App Store).

**Comment by stefanosala** [comment]
It works with skype for example.
I rolled back to 1.2.2 to see notifications work again.

**Comment by alloy** [comment]
Hmm, maybe one of the suggestions in #16 can help. However, unfortunately I won’t have time to work on that in the foreseeable future, care to take a stab at it or take it up with the others on that ticket?

**Comment by alloy** [comment]
For now I have dropped Growl support completely in the version 3.0.0 branch, which will use OS X 10.8’s User Notifications.

Patches add (working) Growl support for other systems will be accepted.
