### ISSUE TITLE
/Users/ejburns/Documents/kicker/lib/kicker.rb:102:in `mtime': Too many levels of symbolic links - /Users/ejburns/Documents/JavaEE/workareas/mojarra-adc/mojarra-1HEAD (Errno::ELOOP)

### ISSUE THREAD

**Issue by edburns** [alloy/kicker#19]
I have no symlinks in the picture.  Here's the story:

uname -a
Darwin dhcp-adc-twvpn-1-vpnpool-10-154-26-196.vpn.oracle.com 11.2.0 Darwin Kernel Version 11.2.0: Tue Aug  9 20:54:00 PDT 2011; root:xnu-1699.24.8~1/RELEASE_X86_64 x86_64

ruby -v
ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-darwin11.2.0]

I just did a clone today.

Here's my ".kick" file:

  process do |files|
    r = ENV['ADC']
    files.each do |src| 
      if ! src.include? ".svn"
    dest = "#{r}/#{src}"
    puts "Copying #{src} to #{dest}"
    execute("cp #{src} #{dest}")
      end
      files.delete(src)
    end
  end

Here is my invocation script, which I call kicker:

export ADC="/net/adc2110030/scratch/ejburns/Documents/JavaEE/workareas/mojarra-1HEAD"
# unzip $ADC/adc.zip

/Users/ejburns/Documents/kicker/bin/kicker /Users/ejburns/Documents/JavaEE/workareas/mojarra-adc

What I want to happen is that when I modify a file in mojarra-adc it gets copied to the same place in mojarra-1HEAD

Note that ADC is auto mounted.  I can write to it successfully manually.

**Comment by edburns** [comment]
Here's the error I get when I write a file

dhcp-adc-twvpn-1-vpnpool-10-154-10-3:mojarra-adc ejburns$ ./kicker
16:02:16.98 | Watching for changes on: /Users/ejburns/Documents/JavaEE/workareas/mojarra-adc
16:02:16.98 | 
/usr/local/rvm/gems/ruby-1.9.3-p0/gems/rb-fsevent-0.4.3.1/lib/rb-fsevent/fsevent.rb:89: warning: Insecure world writable dir /Users/ejburns/Documents in PATH, mode 040777
/Users/ejburns/Documents/kicker/lib/kicker.rb:102:in `mtime': Too many levels of symbolic links - /Users/ejburns/Documents/JavaEE/workareas/mojarra-adc/mojarra-1HEAD (Errno::ELOOP)
    from /Users/ejburns/Documents/kicker/lib/kicker.rb:102:in`file_changed_since_last_event?'
    from /Users/ejburns/Documents/kicker/lib/kicker.rb:91:in `block (2 levels) in changed_files'
    from /Users/ejburns/Documents/kicker/lib/kicker.rb:91:in`select'
    from /Users/ejburns/Documents/kicker/lib/kicker.rb:91:in `block in changed_files'
    from /Users/ejburns/Documents/kicker/lib/kicker.rb:90:in`map'
    from /Users/ejburns/Documents/kicker/lib/kicker.rb:90:in `changed_files'
    from /Users/ejburns/Documents/kicker/lib/kicker.rb:83:in`process'
    from /Users/ejburns/Documents/kicker/lib/kicker.rb:64:in `block in run_watch_dog!'
    from /Users/ejburns/Documents/kicker/lib/kicker/fsevents.rb:28:in`block in start_watching'
    from /usr/local/rvm/gems/ruby-1.9.3-p0/gems/rb-fsevent-0.4.3.1/lib/rb-fsevent/fsevent.rb:37:in `call'
    from /usr/local/rvm/gems/ruby-1.9.3-p0/gems/rb-fsevent-0.4.3.1/lib/rb-fsevent/fsevent.rb:37:in`run'
    from /Users/ejburns/Documents/kicker/lib/kicker/fsevents.rb:30:in `start_watching'
    from /Users/ejburns/Documents/kicker/lib/kicker.rb:63:in`run_watch_dog!'
    from /Users/ejburns/Documents/kicker/lib/kicker.rb:35:in `start'
    from /Users/ejburns/Documents/kicker/lib/kicker.rb:14:in`run'
    from /Users/ejburns/Documents/kicker/bin/kicker:10:in `<main>'

**Comment by Manfred** [comment]
There is probably a looped symlink somewhere in the same directory as the changed file.

The backstory is that we get fsevents for directories and not distinct files, we try to find the changed files for you by looking at the modified time for those files. One of these tests failing. A quick fix for now would be to open op kicker.rb and change line 103 to also rescue Errno::ELOOP.

**Comment by Manfred** [comment]
Closing because this issue is probably stale. Please reopen if it's still a problem.
