### ISSUE TITLE
Bundler instead of Jeweler

### ISSUE THREAD

**Issue by azisaka** [alloy/kicker#20]
Have you ever considered using Bundler instead of Jeweler? I just tried to set up a test environment to give you a patch and it was quite hard to know which gems are requested.

**Comment by Manfred** [comment]
Jeweler is not for dependency management. We use it primarily to set generate gems.

I personally hate Bundler with a passion, but if you want to set up a Gemfile so it's easier to set up for development that would be awesome!

**Comment by azisaka** [comment]
@Manfred I've created the Gemfile, but now I'm getting this error: https://gist.github.com/0b28f19b63b09d143aaa

I think the problem is the test-spec. It seems it's not compatible with Ruby 1.9.x. Would you consider using Minitest::Spec instead?

**Comment by Manfred** [comment]
If you install test/unit on 1.9 test-spec should ‘work’. I won't really mind which spec framework we use, so long it runs both on 1.8 and 1.9.

**Comment by alloy** [comment]
We have a Gemfile nowadays.
