### ISSUE TITLE
Recipe to preserve colored output from commands

### ISSUE THREAD

**Issue by flevour** [alloy/kicker#22]
I am currently trying kicker to launch behat upon a fs change.
Normal output would be http://cl.ly/3K171n3d382F030n1P1h
While inside kicker I get http://cl.ly/2f1v3B12131b191b0O3K

From what you can see is it something I can avoid crafting some specific kicker recipe or do you think it's a problem connected to behat output?

**Comment by flevour** [comment]
Posted too early, it seems it's a behat behaviour, overrideable with --ansi option.
Sorry for all the fuss :)

**Comment by alloy** [comment]
Hey, did adding the `--ansi` option bring back colors?

**Comment by flevour** [comment]
Yes.

**Comment by alloy** [comment]
Thanks.
