### ISSUE TITLE
Test::Unit specific recipe?

### ISSUE THREAD

**Issue by defunkt** [alloy/kicker#3]
Are there any plans for a Test::Unit specific recipe?

I've been using this: http://github.com/defunkt/mustache/blob/master/.kick

It makes the growl messages a bit simpler, cuts out the logging (so you can easily see the failures in the terminal), and stops notifying you when builds start.

**Comment by alloy** [comment]
Yes I'm planning on doing that. At least something very naive that we can build useful stuff upon as we go. (Stuff like red-green, for instance.)

> I've been using this: http://github.com/defunkt/mustache/blob/master/.kick

Cool, I'll use that as a start, it's indeed nicer to only see the relevant output.

Note that if you don't want to see specific growl messages at all, you can specify that in the Growl preferences. Select Kicker in the list of applications and disable the ‘Change occurred’ notification.

**Comment by alloy** [comment]
Forked mustache and updated it for Kicker 2.2.0. Closed by 487c97fcc2b0644861971bd886e52a1b392c1f8e.

**Comment by alloy** [comment]
See http://github.com/alloy/mustache/blob/d34fec9cbc0aefbaa1188ff7e1910d99fbf7f907/.kick

This should give you, roughly, the same results.
