### ISSUE TITLE
Notifications on Linux?

### ISSUE THREAD

**Issue by alloy** [alloy/kicker#30]
@mvz In version 3 I’m dropping Growl support (on OS X) for the new User Notifications. Are notifications something that you would be interested in as well (on Linux)? If so, can you tell me which notification system is the current most accepted one?

**Comment by mvz** [comment]
Yes, notifications would be nice. Gnome uses [Desktop Notification](http://www.galago-project.org/specs/notification/0.9/index.html), which has bindings for Ruby in the form of the [libnotify](https://github.com/splattael/libnotify) gem.

There's also [notify](https://github.com/jugyo/notify), which uses libnotify under the hood if available, or any of a number of other notification systems. That might be useful if you want to support KDE.

**Comment by mikz** [comment]
Version 3.0.0pre2 is using notify which should cover all the major platforms.

**Comment by Manfred** [comment]
Version 3.0 has Inotify support.
