### ISSUE TITLE
Weird situation on syntax errors

### ISSUE THREAD

**Issue by Manfred** [alloy/kicker#34]
When I run Kicker 3.0.0pre1 (on Mountain Lion, zsh) and I get a syntax error from either the test or an implementation file, something weird happens.

The output of the command is send to the terminal-notifier. Because it contains quotes the shell doesn't understand the command and prints an exception.

A solution would be to write the message to terminal-notifier through stdin instead of through an argument.

For an example see:

https://gist.github.com/2efd0e786f51e3a95f0b

**Comment by alloy** [comment]
For Kicker it would probably be easier to escape the message. (I.e. `#inspect` the value.)

**Comment by mikz** [comment]
`pre2` is using notify gem which should cover that
