### ISSUE TITLE
Listen starts in polling mode 

### ISSUE THREAD

**Issue by Manfred** [alloy/kicker#35]
When updated my Gemfile.lock today I lost the rb-fsevent dependency from the lock file. Now when I start Kicker the Listen gem starts in polling mode.

Note that the rb-fsevent gem is still installed so theoretically it could still be loaded, I'm not sure if Bundler lets you load it though.

**Comment by alloy** [comment]
Bundler doesn’t let it do that, I think. Can you see if it works when you add `rb-fsevents` back to your Gemfile?

**Comment by Manfred** [comment]
That only solves the problem if I do bundle exec kicker.

**Comment by alloy** [comment]
Right, because Bundler then explicitly loads the rb-fsevents gem, which is then picked up by the listen gem.

It would seem that the new ‘dependency manager’, in the listen gem, does not actually try to load the rb-fsvents gem, even though it’s installed and available.

**Comment by Manfred** [comment]
This has been solved in more recent versions of Listen.
