### ISSUE TITLE
Any plan to support ML native notifications?

### ISSUE THREAD

**Issue by stefanosala** [alloy/kicker#36]
Hi, as subject it would be nice.
Otherwise, any hint on how to create it and I will try... :)

**Comment by Manfred** [comment]
You could use Eloy's terminal notifier: https://github.com/alloy/terminal-notifier/tree/master/Ruby. The biggest problem we're having with stuff like this is how to support platform dependent gem dependencies.

**Comment by mikz** [comment]
version 3.0.0pre2 is using http://rubygems.org/gems/notify which should cover cross platform notifications

**Comment by Manfred** [comment]
Version 3.0 was just release, so I'm closing this issue.
