### ISSUE TITLE
Minitest support

### ISSUE THREAD

**Issue by mattolson** [alloy/kicker#37]
It would be nice if the default Ruby and Rails recipes supported minitest. This would mean testing for the inclusion of require 'minitest/autorun' in test_helper.rb or the existence of minitest_helper.rb and then using ruby to run the tests. I'm planning to implement this and submit a pull request.

**Comment by mattolson** [comment]
Actually I think the issue I'm having is more a custom application configuration than a general case. I'm using minispec in Rails but following the file system layout described in Railscast #327, which doesn't fall into either the standard test_unit layout for Rails or the rspec layout. I think I will subclass the Rails recipe for my case rather than build in support for something that may not be a common case.

**Comment by Manfred** [comment]
Matt, thanks for mentioning this. We haven't updated the default Rails recipe in some time now, it's possible that it doesn't fully map all the tests currently in Rails 3.2 or in Rails 4. If you find anything missing we would love to hear about it!
