### ISSUE TITLE
Restart Rails application

### ISSUE THREAD

**Issue by alloy** [alloy/kicker#4]
Touch tmp/restart.txt, this assumes Passenger, if files like the following are modified:
- config/environment.rb
- config/environments/development.rb
- config/initializers/*.rb

More?

**Comment by Manfred** [comment]
I don't think starting a background process just to restart Passenger if something changes a file is really worth it. Seems like a task for the Passenger module.

Please close the ticket if you agree (:

**Comment by alloy** [comment]
True :)
