### ISSUE TITLE
need comparison with Guard

### ISSUE THREAD

**Issue by aspiers** [alloy/kicker#40]
At first sight, my naive impression is that kicker reinvents the [Guard](https://github.com/guard/guard) wheel.  There's nothing in the README.md to explain the differences between the two and the motivation for writing / using kicker over Guard.  It would be very helpful if this information was documented.

**Comment by alloy** [comment]
> At first sight, my naive impression is that kicker reinvents the Guard wheel. There's nothing in the README.md to explain the differences between the two and the motivation for writing / using kicker over Guard.

Kicker is about twice the age of Guard.

https://github.com/alloy/kicker/commit/0005e5b032604007f443eefe35d161ff30dfb927 vs https://github.com/guard/guard/commit/4d3744ff43430bdae9dc4b55264912320872fa9a.

> It would be very helpful if this information was documented.

I’m not convinced there should be a comparison in our README. The things Kicker does are simple and outlined in the README. If someone needs something leaner than Guard, then they will know why.

But to satisfy your question on this subject: the bottom-line is that Kicker does roughly the same, except it leaves dealing with (multiple) file events up to you, which makes it more flexible.

HTH.
