### ISSUE TITLE
Kicker silently exits immediately after start

### ISSUE THREAD

**Issue by paulspringett** [alloy/kicker#43]
``` shell
% kicker -r rails -b 'spin push'   
14:28:50.95 | Watching for changes on: /path/to/rails/app
14:28:50.95 | 
% 
```

When running `kicker -r rails -b 'spin push'`, the program silently exits without an error (looks like a zero exit code).

I'm running `ruby 2.0.0p195`, kicker `2.6.1`

**Comment by mikz** [comment]
Could you try `3.0.0.pre2` ? You can install it by `gem install kicker --pre`. It should be fixed there.
In case you find some issues with that pre version feel free to post them here.

**Comment by paulspringett** [comment]
Hi @mikz yep `3.0.0.pre2` works great, thank you for your help.

**Comment by glyph** [comment]
For what it's worth: I also hit this issue, upgrade also fixed it for me.  Is a release impending?

**Comment by mikz** [comment]
I still wanted to do some cross platform testing before releasing stable version. Which platform are you using @glyph ?
