### ISSUE TITLE
Filename interpolation into repeated command

### ISSUE THREAD

**Issue by Olivia5k** [alloy/kicker#49]
I run tests with kicker. I just realized that it would be very cool if kicker could pass the filename of the file that triggered the event into the command!

Imagine I run `kicker -ce "hax0r_tests %s"` and I save `tests/test_lazerguns.py` in my favorite `$EDITOR`. kicker would then execute `hax0r_tests tests/test_lazerguns.py`, in which the test runner will only run the tests in that file, making the feedback loop shorter and the developer happier!

Would this be possible to implement?

**Comment by beporter** [comment]
This would make "ghetto testing" on a per-file basis much easier. +1
