### ISSUE TITLE
kicker -r rails just displays a usage message

### ISSUE THREAD

**Issue by eostrom** [alloy/kicker#5]
Just installed kicker 2.2.0. When I run `kicker -r rails`, I just get the usage message. Likewise `kicker -r rails .` (both commands executing in a Rails directory, of course). Am I missing something about how to run the command, or is something else going wrong?

**Comment by alloy** [comment]
Revert "Show help banner if the startup chain is empty." Closed by 2e540ca3757f8aa9efb6aaa751f55069f073729d.

This reverts commit 608723f4cb99e2cd1faba8f618359e0e03fa53eb.

**Comment by alloy** [comment]
That was an embarrassing bug, thanks for reporting it :)

Just pushed 2.2.1 to gemcutter.
