### ISSUE TITLE
Cross-platform version

### ISSUE THREAD

**Issue by NV** [alloy/kicker#7]
Would be nice if kicker worked on Linux, FreeBSD, and Windows. [em-dir-watcher](https://github.com/mockko/em-dir-watcher) might help with that.

**Comment by Manfred** [comment]
We only use Mac OS, so I'm afraid we will not be working on support for other platforms. If you create a port for your platform of choice we'll be happy to consider including it.

**Comment by alloy** [comment]
What Manfred said is true. However, I wanted to take a look at this anyways, also because I want to get rid of the RubyCocoa dependency.

**Comment by Manfred** [comment]
I guess we could abstract the events backend a bit so people can write their own even providers like we did with Miso.

**Comment by alloy** [comment]
Just merged #23. If no issues crop up we'll release this next week or so.
